server:
  port: 8080
spring:
  application:
    name: "reportes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
entrypoint:
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/637423566812/solicitudes-aprobadas"
    waitTimeSeconds: 10
    maxNumberOfMessages: 5
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
